---
fixtures:
  repositories:
    iptables: https://github.com/simp/pupmod-simp-iptables
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    java: https://github.com/simp/puppetlabs-java
  symlinks:
    hirs_provisioner: "#{source_dir}"
