<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7-tpm-1-2:
    roles:
      - default
      - hirs
      - tpm_1_2
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  el7-tpm-2-0:
    roles:
      - hirs
      - tpm_2_0
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  el6-tpm-1-2:
    roles:
      - hirs
      - tpm_1_2
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  aca:
    roles:
      - aca
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
