<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7-tpm-2-0.beaker.test:
    roles:
      - default
      - hirs
      - tpm_2_0
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      simp_rolling:
        baseurl: 'https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp/'
        gpgcheck: 0

  aca:
    roles:
      - aca
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
